/*!
 * @file pirple_skillsspells_.h
 * @brief Internal and system definitions for the game. Skills and spells.
 * @author Joe Vail
 * @copyright Copyright (c) 2018 jvindy software under the PirpleMUD License.@n
 * PirpleMUD is based on CircleMUD, Copyright(c) 1995.@n
 * CircleMUD is based on DikuMUD, Copyright(c) 1990, 1991.@n
 * See @ref LICENSE file for more information.
 */

#ifndef PIRPLEMUD_SKILLSSPELLS_H
#define PIRPLEMUD_SKILLSSPELLS_H

#include "pirple_.h"

namespace Pirple
{

enum SPELL
{
    SPELL_NONE = 0,
    SPELL_ARMOR,
    SPELL_TELEPORT,
    SPELL_BLESS,
    SPELL_BLINDNESS,
    SPELL_BURNING_HANDS,
    SPELL_CALL_LIGHTNING,
    SPELL_CHARM,
    SPELL_CHILL_TOUCH,
    SPELL_CLONE,
    SPELL_COLOR_SPRAY,
    SPELL_CONTROL_WEATHER,
    SPELL_CREATE_FOOD,
    SPELL_CREATE_WATER,
    SPELL_CURE_BLIND,
    SPELL_CURE_CRITIC,
    SPELL_CURE_LIGHT,
    SPELL_CURSE,
    SPELL_DETECT_ALIGNMENT,
    SPELL_DETECT_INVISIBLE,
    SPELL_DETECT_MAGIC,
    SPELL_DETECT_POISON,
    SPELL_DISPEL_EVIL,
    SPELL_EARTHQUAKE,
    SPELL_ENCHANT_WEAPON,
    SPELL_ENERGY_DRAIN,
    SPELL_FIREBALL,
    SPELL_HARM,
    SPELL_HEAL,
    SPELL_INVISIBLE,
    SPELL_LIGHTNING_BOLT,
    SPELL_LOCATE_OBJECT,
    SPELL_MAGIC_MISSILE,
    SPELL_POISON,
    SPELL_PROTECTION_FROM_EVIL,
    SPELL_REMOVE_CURSE,
    SPELL_SANCTUARY,
    SPELL_SHOCKING_GRASP,
    SPELL_SLEEP,
    SPELL_STRENGTH,
    SPELL_SUMMON,
    SPELL_VENTRILOQUATE,
    SPELL_WORD_OF_RECALL,
    SPELL_REMOVE_POISON,
    SPELL_SENSE_LIFE,
    SPELL_ANIMATE_DEAD,
    SPELL_DISPEL_GOOD,
    SPELL_GROUP_ARMOR,
    SPELL_GROUP_HEAL,
    SPELL_GROUP_RECALL,
    SPELL_INFRAVISION,
    SPELL_WATERWALK,
    SPELL_IDENTIFY,
    SPELL_FIRE_BREATH,
    SPELL_GAS_BREATH,
    SPELL_FROST_BREATH,
    SPELL_ACID_BREATH,
    SPELL_LIGHTNING_BREATH
};
enum { NUM_SPELLS = SPELL_LIGHTNING_BREATH + 1 };

enum SKILL
{
    SKILL_NONE = 0,
    SKILL_BACKSTAB,
    SKILL_BASH,
    SKILL_HIDE,
    SKILL_KICK,
    SKILL_PICK_LOCK,
    SKILL_RESCUE,
    SKILL_SNEAK,
    SKILL_STEAL,
    SKILL_TRACK
};
enum { NUM_SKILLS = SKILL_TRACK + 1 };

}

#endif // PIRPLEMUD_SKILLSSPELLS_H
